apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: test
spec:
  master:
   image: jenkins/jenkins
  seedJobs:
  - id: test
    targets: "cicd/jobs/*.jenkins"
    description: "Test"
    repositoryBranch: master
    repositoryUrl: https://github.com/zlatra/test.git
